[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7865BAC30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9a44bdfcf6cac0682ba7b56928a55c6f/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7865B8650>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9a44bdfcf6cac0682ba7b56928a55c6f/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7865B9F70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9a44bdfcf6cac0682ba7b56928a55c6f/screenshot